# Generated by Django 5.2.3 on 2025-11-30 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrudentialReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporting_period', models.DateField()),
                ('submission_date', models.DateField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('smi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.smi')),
            ],
        ),
        migrations.CreateModel(
            name='IncomeStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=15)),
                ('operating_expenses', models.DecimalField(decimal_places=2, max_digits=15)),
                ('net_profit', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prudential_return', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='returns_module.prudentialreturn')),
            ],
        ),
        migrations.CreateModel(
            name='BalanceSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_assets', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_liabilities', models.DecimalField(decimal_places=2, max_digits=15)),
                ('equity', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prudential_return', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='returns_module.prudentialreturn')),
            ],
        ),
    ]
