# Generated by Django 5.2.3 on 2025-08-22 18:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'Administrator'), ('PRINCIPAL_OFFICER', 'Principal Officer'), ('ACCOUNTANT', 'Accountant'), ('COMPLIANCE_OFFICER', 'Compliance Officer')], max_length=50)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('smi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.smi')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('can_view_smi_data', 'Can view SMI data'), ('can_edit_smi_data', 'Can edit SMI data'), ('can_view_reports', 'Can view reports'), ('can_create_reports', 'Can create reports')],
            },
        ),
    ]
