# Generated by Django 5.2.5 on 2025-08-27 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_module', '0002_userprofile_department_userprofile_last_login_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='last_login',
        ),
    ]
