# Generated by Django 5.2.3 on 2025-12-01 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complianceindex',
            name='negative_weight',
            field=models.FloatField(default=1.0, help_text='Bi: Negative weight'),
        ),
        migrations.AddField(
            model_name='complianceindex',
            name='positive_weight',
            field=models.FloatField(default=1.0, help_text='Pi: Positive weight'),
        ),
        migrations.AddField(
            model_name='complianceindex',
            name='total_blank',
            field=models.IntegerField(default=0, help_text='B: Total number of Blank answers'),
        ),
        migrations.AddField(
            model_name='complianceindex',
            name='total_no',
            field=models.IntegerField(default=0, help_text='N: Total number of No answers'),
        ),
        migrations.AddField(
            model_name='complianceindex',
            name='total_responses',
            field=models.IntegerField(default=0, help_text='R: Total number of Responses'),
        ),
        migrations.AddField(
            model_name='complianceindex',
            name='total_yes',
            field=models.IntegerField(default=0, help_text='Y: Total number of Yes answers'),
        ),
    ]
