# Generated by Django 5.2.3 on 2025-08-27 20:54

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance_module', '0001_initial'),
        ('core', '0002_remove_casenote_case_remove_casenote_author_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complianceassessment',
            options={'ordering': ['-assessment_date']},
        ),
        migrations.AlterModelOptions(
            name='complianceindex',
            options={'ordering': ['-period']},
        ),
        migrations.AlterModelOptions(
            name='compliancereport',
            options={'ordering': ['-report_date']},
        ),
        migrations.AlterModelOptions(
            name='compliancerequirement',
            options={'ordering': ['due_date', 'priority']},
        ),
        migrations.AlterModelOptions(
            name='complianceviolation',
            options={'ordering': ['-date_identified']},
        ),
        migrations.RemoveConstraint(
            model_name='complianceindex',
            name='compliance_module_complianceindex_unique_smi_period_analysis',
        ),
        migrations.AlterField(
            model_name='complianceassessment',
            name='action_items',
            field=models.JSONField(default=list, help_text='List of required actions'),
        ),
        migrations.AlterField(
            model_name='complianceassessment',
            name='assessment_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='complianceassessment',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='complianceassessment',
            name='risk_areas',
            field=models.JSONField(default=dict, help_text='Areas like CDD, record-keeping, reporting compliance'),
        ),
        migrations.AlterField(
            model_name='complianceassessment',
            name='smi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_assessments', to='core.smi'),
        ),
        migrations.AlterField(
            model_name='complianceindex',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='complianceindex',
            name='period',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='complianceindex',
            name='risk_adjustment_factor',
            field=models.FloatField(default=1.0, help_text='Factor applied based on inspection results'),
        ),
        migrations.AlterField(
            model_name='complianceindex',
            name='smi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_indices', to='core.smi'),
        ),
        migrations.AlterField(
            model_name='compliancereport',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='compliancereport',
            name='smi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_reports', to='core.smi'),
        ),
        migrations.AlterField(
            model_name='compliancerequirement',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='compliancerequirement',
            name='smi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_requirements', to='core.smi'),
        ),
        migrations.AlterField(
            model_name='complianceviolation',
            name='compliance_requirement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='compliance_module.compliancerequirement'),
        ),
        migrations.AlterField(
            model_name='complianceviolation',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='complianceviolation',
            name='smi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_violations', to='core.smi'),
        ),
    ]
