# Generated by Django 5.2.5 on 2025-08-28 00:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_management_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='opened_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
