# Generated by Django 5.2.5 on 2025-08-28 00:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_management_module', '0002_alter_case_opened_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investigation',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
