# Generated by Django 5.2.3 on 2025-12-02 06:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('is_current', models.BooleanField(default=True)),
                ('acquisition_date', models.DateField(blank=True, null=True)),
                ('financial_statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='core.financialstatement')),
            ],
        ),
        migrations.CreateModel(
            name='CapitalPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculation_date', models.DateField()),
                ('net_capital', models.DecimalField(decimal_places=2, max_digits=15)),
                ('required_capital', models.DecimalField(decimal_places=2, max_digits=15)),
                ('adjusted_liquid_capital', models.DecimalField(decimal_places=2, max_digits=15)),
                ('is_compliant', models.BooleanField(default=True)),
                ('capital_adequacy_ratio', models.FloatField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('smi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capital_positions', to='core.smi')),
            ],
        ),
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('purpose', models.TextField()),
                ('chairperson', models.CharField(max_length=255)),
                ('members', models.JSONField(default=list, help_text='List of member names')),
                ('meetings_held', models.IntegerField(default=0)),
                ('meeting_frequency', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('smi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='committees', to='core.smi')),
            ],
        ),
        migrations.CreateModel(
            name='Creditor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('due_date', models.DateField()),
                ('financial_statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creditors', to='core.financialstatement')),
            ],
        ),
        migrations.CreateModel(
            name='Debtor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('age_days', models.IntegerField()),
                ('financial_statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debtors', to='core.financialstatement')),
            ],
        ),
        migrations.CreateModel(
            name='IncomeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('is_core', models.BooleanField(default=True)),
                ('financial_statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income_items', to='core.financialstatement')),
            ],
        ),
        migrations.CreateModel(
            name='Liability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liability_type', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('is_current', models.BooleanField(default=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('financial_statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liabilities', to='core.financialstatement')),
            ],
        ),
        migrations.CreateModel(
            name='RelatedParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('relationship', models.CharField(max_length=255)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('transaction_type', models.CharField(choices=[('receivable', 'Receivable'), ('payable', 'Payable')], max_length=20)),
                ('financial_statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_parties', to='core.financialstatement')),
            ],
        ),
    ]
