# Generated by Django 5.2.5 on 2025-08-27 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casenote',
            name='case',
        ),
        migrations.RemoveField(
            model_name='casenote',
            name='author',
        ),
        migrations.AlterUniqueTogether(
            name='complianceindex',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='complianceindex',
            name='smi',
        ),
        migrations.RemoveField(
            model_name='inspectionreport',
            name='inspector',
        ),
        migrations.RemoveField(
            model_name='inspectionreport',
            name='smi',
        ),
        migrations.AlterUniqueTogether(
            name='riskassessment',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='riskassessment',
            name='assessor',
        ),
        migrations.RemoveField(
            model_name='riskassessment',
            name='smi',
        ),
        migrations.RemoveField(
            model_name='stresstest',
            name='smi',
        ),
        migrations.RemoveField(
            model_name='va_vasp',
            name='smi',
        ),
        migrations.DeleteModel(
            name='Case',
        ),
        migrations.DeleteModel(
            name='CaseNote',
        ),
        migrations.DeleteModel(
            name='ComplianceIndex',
        ),
        migrations.DeleteModel(
            name='InspectionReport',
        ),
        migrations.DeleteModel(
            name='RiskAssessment',
        ),
        migrations.DeleteModel(
            name='StressTest',
        ),
        migrations.DeleteModel(
            name='VA_VASP',
        ),
    ]
