# Generated by Django 5.2.5 on 2025-08-27 23:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_casenote_case_remove_casenote_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smi',
            name='registration_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
