# Generated by Django 5.2.5 on 2025-08-27 23:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_assessment_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stresstest',
            name='test_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
