# Generated by Django 5.2.5 on 2025-08-28 10:20

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_alter_smi_registration_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='LicensingPortalIntegration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('portal_name', models.CharField(default='Licensing Portal', max_length=255)),
                ('api_endpoint', models.URLField(default='https://api.licensing-portal.com')),
                ('api_key', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('ERROR', 'Error'), ('MAINTENANCE', 'Under Maintenance')], default='ACTIVE', max_length=20)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('sync_frequency', models.CharField(choices=[('HOURLY', 'Hourly'), ('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MANUAL', 'Manual')], default='DAILY', max_length=20)),
                ('auto_sync_enabled', models.BooleanField(default=True)),
                ('sync_errors', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('director_type', models.CharField(choices=[('EXECUTIVE', 'Executive Director'), ('NON_EXECUTIVE', 'Non-Executive Director'), ('INDEPENDENT', 'Independent Director'), ('CHAIRMAN', 'Chairman'), ('CEO', 'Chief Executive Officer'), ('CFO', 'Chief Financial Officer'), ('COO', 'Chief Operating Officer'), ('CRO', 'Chief Risk Officer'), ('CCO', 'Chief Compliance Officer')], default='EXECUTIVE', max_length=20)),
                ('nationality', models.CharField(blank=True, max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('qualifications', models.TextField(blank=True)),
                ('experience_years', models.IntegerField(default=0)),
                ('previous_positions', models.JSONField(default=list)),
                ('appointment_date', models.DateField()),
                ('resignation_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('regulatory_approval', models.BooleanField(default=False)),
                ('approval_date', models.DateField(blank=True, null=True)),
                ('fit_and_proper_assessment', models.CharField(choices=[('PASSED', 'Passed'), ('FAILED', 'Failed'), ('PENDING', 'Pending'), ('NOT_ASSESSED', 'Not Assessed')], default='NOT_ASSESSED', max_length=20)),
                ('training_completed', models.BooleanField(default=False)),
                ('last_training_date', models.DateField(blank=True, null=True)),
                ('compliance_status', models.CharField(choices=[('COMPLIANT', 'Compliant'), ('NON_COMPLIANT', 'Non-Compliant'), ('UNDER_REVIEW', 'Under Review')], default='UNDER_REVIEW', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('smi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directors', to='core.smi')),
            ],
            options={
                'ordering': ['appointment_date'],
            },
        ),
        migrations.CreateModel(
            name='InstitutionalProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('business_model', models.TextField(default='Business model to be described')),
                ('target_markets', models.JSONField(default=list, help_text='List of target markets')),
                ('competitive_position', models.CharField(choices=[('MARKET_LEADER', 'Market Leader'), ('MAJOR_PLAYER', 'Major Player'), ('MID_TIER', 'Mid-tier'), ('SMALL_PLAYER', 'Small Player'), ('NICHE', 'Niche Player')], default='MID_TIER', max_length=100)),
                ('credit_rating', models.CharField(blank=True, max_length=10)),
                ('debt_rating', models.CharField(blank=True, max_length=10)),
                ('financial_strength', models.CharField(choices=[('EXCELLENT', 'Excellent'), ('GOOD', 'Good'), ('SATISFACTORY', 'Satisfactory'), ('WEAK', 'Weak'), ('POOR', 'Poor')], default='SATISFACTORY', max_length=20)),
                ('risk_appetite', models.CharField(choices=[('CONSERVATIVE', 'Conservative'), ('MODERATE', 'Moderate'), ('AGGRESSIVE', 'Aggressive'), ('VERY_AGGRESSIVE', 'Very Aggressive')], default='MODERATE', max_length=20)),
                ('number_of_employees', models.IntegerField(default=0)),
                ('number_of_branches', models.IntegerField(default=0)),
                ('operating_countries', models.JSONField(default=list)),
                ('compliance_history', models.TextField(blank=True)),
                ('regulatory_relationships', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('smi', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='institutional_profile', to='core.smi')),
            ],
        ),
        migrations.CreateModel(
            name='LicenseHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('change_type', models.CharField(choices=[('GRANTED', 'License Granted'), ('RENEWED', 'License Renewed'), ('AMENDED', 'License Amended'), ('SUSPENDED', 'License Suspended'), ('REVOKED', 'License Revoked'), ('RESTORED', 'License Restored'), ('EXPIRED', 'License Expired')], default='GRANTED', max_length=20)),
                ('change_date', models.DateField()),
                ('effective_date', models.DateField()),
                ('license_number', models.CharField(max_length=100)),
                ('license_type', models.CharField(max_length=100)),
                ('license_scope', models.TextField()),
                ('license_conditions', models.JSONField(default=list)),
                ('regulatory_authority', models.CharField(max_length=255)),
                ('approval_reference', models.CharField(blank=True, max_length=255)),
                ('regulatory_officer', models.CharField(blank=True, max_length=255)),
                ('license_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('security_deposit', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('renewal_due_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('smi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='license_history', to='core.smi')),
            ],
            options={
                'ordering': ['-change_date'],
            },
        ),
        migrations.CreateModel(
            name='PortalSMIData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('portal_id', models.CharField(max_length=100, unique=True)),
                ('portal_status', models.CharField(default='Active', max_length=50)),
                ('last_updated_from_portal', models.DateTimeField(auto_now=True)),
                ('portal_capital_adequacy', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('portal_licensing_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('portal_annual_revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('portal_created_date', models.DateField(blank=True, null=True)),
                ('portal_last_review_date', models.DateField(blank=True, null=True)),
                ('portal_next_review_date', models.DateField(blank=True, null=True)),
                ('sync_status', models.CharField(choices=[('SYNCED', 'Synced'), ('PENDING', 'Pending'), ('FAILED', 'Failed'), ('OUTDATED', 'Outdated')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('smi', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portal_data', to='core.smi')),
            ],
        ),
        migrations.CreateModel(
            name='Shareholder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('shareholder_type', models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('CORPORATE', 'Corporate'), ('GOVERNMENT', 'Government'), ('INSTITUTIONAL', 'Institutional'), ('FOREIGN', 'Foreign Entity')], default='INDIVIDUAL', max_length=20)),
                ('nationality', models.CharField(blank=True, max_length=100)),
                ('ownership_percentage', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('shares_held', models.IntegerField(default=0)),
                ('voting_rights', models.BooleanField(default=True)),
                ('investment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('investment_date', models.DateField(blank=True, null=True)),
                ('regulatory_approval', models.BooleanField(default=False)),
                ('approval_date', models.DateField(blank=True, null=True)),
                ('approval_reference', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('smi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shareholders', to='core.smi')),
            ],
            options={
                'ordering': ['-ownership_percentage'],
            },
        ),
    ]
