# Generated by Django 5.2.3 on 2025-11-30 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('licensing_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='institutionalprofile',
            options={'ordering': ['-created_at']},
        ),
    ]
